# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import records_pb2 as records__pb2


class PatientRecordsServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetPatientInfo = channel.unary_unary(
                '/records.PatientRecordsService/GetPatientInfo',
                request_serializer=records__pb2.GetPatientInfoRequest.SerializeToString,
                response_deserializer=records__pb2.Patient.FromString,
                )
        self.UpdatePatientInfo = channel.unary_unary(
                '/records.PatientRecordsService/UpdatePatientInfo',
                request_serializer=records__pb2.UpdatePatientInfoRequest.SerializeToString,
                response_deserializer=records__pb2.Patient.FromString,
                )


class PatientRecordsServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetPatientInfo(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdatePatientInfo(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PatientRecordsServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetPatientInfo': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPatientInfo,
                    request_deserializer=records__pb2.GetPatientInfoRequest.FromString,
                    response_serializer=records__pb2.Patient.SerializeToString,
            ),
            'UpdatePatientInfo': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdatePatientInfo,
                    request_deserializer=records__pb2.UpdatePatientInfoRequest.FromString,
                    response_serializer=records__pb2.Patient.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'records.PatientRecordsService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class PatientRecordsService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetPatientInfo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/records.PatientRecordsService/GetPatientInfo',
            records__pb2.GetPatientInfoRequest.SerializeToString,
            records__pb2.Patient.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def UpdatePatientInfo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/records.PatientRecordsService/UpdatePatientInfo',
            records__pb2.UpdatePatientInfoRequest.SerializeToString,
            records__pb2.Patient.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
