# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: records.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rrecords.proto\x12\x07records\"<\n\x07Patient\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x17\n\x0fmedical_history\x18\x03 \x01(\t\"+\n\x15GetPatientInfoRequest\x12\x12\n\npatient_id\x18\x01 \x01(\t\"O\n\x18UpdatePatientInfoRequest\x12\x12\n\npatient_id\x18\x01 \x01(\t\x12\x1f\n\x17updated_medical_history\x18\x02 \x01(\t2\xa5\x01\n\x15PatientRecordsService\x12\x42\n\x0eGetPatientInfo\x12\x1e.records.GetPatientInfoRequest\x1a\x10.records.Patient\x12H\n\x11UpdatePatientInfo\x12!.records.UpdatePatientInfoRequest\x1a\x10.records.Patientb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'records_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_PATIENT']._serialized_start=26
  _globals['_PATIENT']._serialized_end=86
  _globals['_GETPATIENTINFOREQUEST']._serialized_start=88
  _globals['_GETPATIENTINFOREQUEST']._serialized_end=131
  _globals['_UPDATEPATIENTINFOREQUEST']._serialized_start=133
  _globals['_UPDATEPATIENTINFOREQUEST']._serialized_end=212
  _globals['_PATIENTRECORDSSERVICE']._serialized_start=215
  _globals['_PATIENTRECORDSSERVICE']._serialized_end=380
# @@protoc_insertion_point(module_scope)
