# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: registration.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12registration.proto\x12\x0cregistration\x1a\x1bgoogle/protobuf/empty.proto\"?\n\x13ServiceRegistration\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0c\n\x04host\x18\x02 \x01(\t\x12\x0c\n\x04port\x18\x03 \x01(\x05\"D\n\x18\x44\x65registerServiceRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0c\n\x04host\x18\x02 \x01(\t\x12\x0c\n\x04port\x18\x03 \x01(\x05\">\n\x18SendServiceStatusRequest\x12\x14\n\x0cservice_name\x18\x01 \x01(\t\x12\x0c\n\x04load\x18\x02 \x01(\x05\"!\n\tHeartbeat\x12\x14\n\x0cservice_name\x18\x01 \x01(\t2\xda\x02\n\x13RegistrationService\x12L\n\x0fRegisterService\x12!.registration.ServiceRegistration\x1a\x16.google.protobuf.Empty\x12S\n\x11\x44\x65registerService\x12&.registration.DeregisterServiceRequest\x1a\x16.google.protobuf.Empty\x12U\n\x13UpdateServiceStatus\x12&.registration.SendServiceStatusRequest\x1a\x16.google.protobuf.Empty\x12I\n\x16UpdateServiceHeartbeat\x12\x17.registration.Heartbeat\x1a\x16.google.protobuf.Emptyb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'registration_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_SERVICEREGISTRATION']._serialized_start=65
  _globals['_SERVICEREGISTRATION']._serialized_end=128
  _globals['_DEREGISTERSERVICEREQUEST']._serialized_start=130
  _globals['_DEREGISTERSERVICEREQUEST']._serialized_end=198
  _globals['_SENDSERVICESTATUSREQUEST']._serialized_start=200
  _globals['_SENDSERVICESTATUSREQUEST']._serialized_end=262
  _globals['_HEARTBEAT']._serialized_start=264
  _globals['_HEARTBEAT']._serialized_end=297
  _globals['_REGISTRATIONSERVICE']._serialized_start=300
  _globals['_REGISTRATIONSERVICE']._serialized_end=646
# @@protoc_insertion_point(module_scope)
