# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import prescription_pb2 as prescription__pb2


class PrescriptionManagementServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreatePrescription = channel.unary_unary(
                '/prescription.PrescriptionManagementService/CreatePrescription',
                request_serializer=prescription__pb2.CreatePrescriptionRequest.SerializeToString,
                response_deserializer=prescription__pb2.Prescription.FromString,
                )
        self.SendPrescriptionByEmail = channel.unary_unary(
                '/prescription.PrescriptionManagementService/SendPrescriptionByEmail',
                request_serializer=prescription__pb2.SendPrescriptionByEmailRequest.SerializeToString,
                response_deserializer=prescription__pb2.Prescription.FromString,
                )


class PrescriptionManagementServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CreatePrescription(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SendPrescriptionByEmail(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PrescriptionManagementServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreatePrescription': grpc.unary_unary_rpc_method_handler(
                    servicer.CreatePrescription,
                    request_deserializer=prescription__pb2.CreatePrescriptionRequest.FromString,
                    response_serializer=prescription__pb2.Prescription.SerializeToString,
            ),
            'SendPrescriptionByEmail': grpc.unary_unary_rpc_method_handler(
                    servicer.SendPrescriptionByEmail,
                    request_deserializer=prescription__pb2.SendPrescriptionByEmailRequest.FromString,
                    response_serializer=prescription__pb2.Prescription.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'prescription.PrescriptionManagementService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class PrescriptionManagementService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CreatePrescription(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/prescription.PrescriptionManagementService/CreatePrescription',
            prescription__pb2.CreatePrescriptionRequest.SerializeToString,
            prescription__pb2.Prescription.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SendPrescriptionByEmail(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/prescription.PrescriptionManagementService/SendPrescriptionByEmail',
            prescription__pb2.SendPrescriptionByEmailRequest.SerializeToString,
            prescription__pb2.Prescription.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
